---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim2
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
  labels:
    app: {{ .Values.namept }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi




