apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-extensions2
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 9Gi


