apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-data2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 9Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs: 
    path: /kubedata 
    server: 192.168.48.139 
