apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-extensions2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 9Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarext-pv2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/nfs/kubedata
    server: 192.168.48.139

