
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-data2
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 9Gi

