{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.nexus.name }}
  namespace: nexus
spec:
  rules:
  - host: {{ .Values.nexus.hosts.host }}
    http:
      paths: {{- range .Values.nexus.hosts.paths }}
        - path: /
          pathType: Prefix
          backend:
            serviceName: {{ .service.name }}
            servicePort: {{ .service.port }}
        {{- end }}
{{- end }}
