apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: {{ .Values.namept }}
data:
  POSTGRES_DB: {{ .Values.data.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.data.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.data.POSTGRES_PASSWORD }}

